"""aae_observability public API."""

from aae_observability._version import __version__
from aae_observability.adapters import (
    LangChainAdapter,
    MicrosoftAgentFrameworkAdapter,
    MultiAgentAdapter,
    build_adapter_registry,
    default_adapters,
    discover_adapters,
)
from aae_observability.api import (
    configure,
    get_config_reloader,
    get_governance_report,
    instrument,
    is_configured,
    shutdown,
)
from aae_observability.config import (
    AaeObservabilityConfig,
    CredentialConfigurationError,
    EnvironmentConfigError,
    GovernanceConfig,
    KeyVaultSecretResolver,
    ReloadEvent,
    ReloadSnapshot,
    RuntimeConfigReloader,
    SecretResolutionError,
    SecretResolver,
    TelemetryConfig,
    TokenCredential,
    build_azure_credential,
    build_layered_reloader,
    environment_overrides,
    load_config,
    load_layered_config,
    resolve_telemetry_secrets,
)
from aae_observability.contracts import (
    ActionSnapshot,
    AgentCall,
    AllowAllPolicyEngine,
    BaseFrameworkAdapter,
    BasePolicyEngine,
    BaseTelemetrySink,
    DenyAllPolicyEngine,
    Framework,
    FrameworkAdapter,
    GenericFrameworkAdapter,
    Identity,
    NullTelemetrySink,
    OperationType,
    PolicyEngine,
    TelemetrySink,
)
from aae_observability.governance import (
    ACSPolicyEngine,
    LocalPolicyEngine,
    PolicyDocument,
    PolicyFileError,
    PolicyRule,
    compile_condition,
    load_policy,
)
from aae_observability.governance.audit import (
    AuditExporterStats,
    GovernanceAuditRecord,
    GovernanceAuditSink,
    InMemoryGovernanceAuditSink,
    JsonLinesGovernanceAuditSink,
)
from aae_observability.governance.enforcement import (
    GovernanceDeniedError,
    GovernanceEvaluationError,
    GovernanceTimeoutError,
)
from aae_observability.governance.report import (
    CompositeGovernanceAuditSink,
    GovernanceReport,
    GovernanceReportSnapshot,
)
from aae_observability.governance.telemetry import GovernanceMetrics
from aae_observability.resource import build_resource, sdk_available
from aae_observability.telemetry import (
    BufferedTelemetrySink,
    BufferMetrics,
    BufferStats,
    SignalType,
    TelemetryBuffer,
    TelemetryEnvelope,
)
from aae_observability.types import PolicyResult, Verdict

__all__ = [
    "ACSPolicyEngine",
    "AaeObservabilityConfig",
    "ActionSnapshot",
    "AgentCall",
    "AllowAllPolicyEngine",
    "AuditExporterStats",
    "BaseFrameworkAdapter",
    "BasePolicyEngine",
    "BaseTelemetrySink",
    "BufferMetrics",
    "BufferStats",
    "BufferedTelemetrySink",
    "CompositeGovernanceAuditSink",
    "CredentialConfigurationError",
    "DenyAllPolicyEngine",
    "EnvironmentConfigError",
    "Framework",
    "FrameworkAdapter",
    "GenericFrameworkAdapter",
    "GovernanceAuditRecord",
    "GovernanceAuditSink",
    "GovernanceConfig",
    "GovernanceDeniedError",
    "GovernanceEvaluationError",
    "GovernanceMetrics",
    "GovernanceReport",
    "GovernanceReportSnapshot",
    "GovernanceTimeoutError",
    "Identity",
    "InMemoryGovernanceAuditSink",
    "JsonLinesGovernanceAuditSink",
    "KeyVaultSecretResolver",
    "LangChainAdapter",
    "LocalPolicyEngine",
    "MicrosoftAgentFrameworkAdapter",
    "MultiAgentAdapter",
    "NullTelemetrySink",
    "OperationType",
    "PolicyDocument",
    "PolicyEngine",
    "PolicyFileError",
    "PolicyResult",
    "PolicyRule",
    "ReloadEvent",
    "ReloadSnapshot",
    "RuntimeConfigReloader",
    "SecretResolutionError",
    "SecretResolver",
    "SignalType",
    "TelemetryBuffer",
    "TelemetryConfig",
    "TelemetryEnvelope",
    "TelemetrySink",
    "TokenCredential",
    "Verdict",
    "__version__",
    "build_adapter_registry",
    "build_azure_credential",
    "build_layered_reloader",
    "build_resource",
    "compile_condition",
    "configure",
    "default_adapters",
    "discover_adapters",
    "environment_overrides",
    "get_config_reloader",
    "get_governance_report",
    "instrument",
    "is_configured",
    "load_config",
    "load_layered_config",
    "load_policy",
    "resolve_telemetry_secrets",
    "sdk_available",
    "shutdown",
]
